all:
  children:
    locust_master:
      hosts:
        locust-master:
          ansible_host: 10.10.7.222
          ansible_connection: local
    locust_workers:
      hosts:
        locust-worker-01:
          ansible_host: 10.10.7.48
        locust-worker-02:
          ansible_host: 10.10.7.96
        locust-worker-03:
          ansible_host: 10.10.7.54
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
